print('''
*******************************************************************************
          |                   |                  |                     |
 _________|________________.=""_;=.______________|_____________________|_______
|                   |  ,-"_,=""     `"=.|                  |
|___________________|__"=._o`"-._        `"=.______________|___________________
          |                `"=._o`"=._      _`"=._                     |
 _________|_____________________:=._o "=._."_.-="'"=.__________________|_______
|                   |    __.--" , ; `"=._o." ,-"""-._ ".   |
|___________________|_._"  ,. .` ` `` ,  `"-._"-._   ". '__|___________________
          |           |o`"=._` , "` `; .". ,  "-._"-._; ;              |
 _________|___________| ;`-.o`"=._; ." ` '`."\ ` . "-._ /_______________|_______
|                   | |o ;    `"-.o`"=._``  '` " ,__.--o;   |
|___________________|_| ;     (#) `-.o `"=.`_.--"_o.-; ;___|___________________
____/______/______/___|o;._    "      `".o|o_.--"    ;o;____/______/______/____
/______/______/______/_"=._o--._        ; | ;        ; ;/______/______/______/_
____/______/______/______/__"=._o--._   ;o|o;     _._;o;____/______/______/____
/______/______/______/______/____"=._o._; | ;_.--"o.--"_/______/______/______/_
____/______/______/______/______/_____"=.o|o_.--""___/______/______/______/____
/______/______/______/______/______/______/______/______/______/______/_____ /
*******************************************************************************
''')
print("Welcome to Treasure Island.")
print("Your mission is to find the treasure.")
print("you find yourself in a dark damp cave. There are two paths.")

chosen_path = input("Do you go left or right? ")
if chosen_path =="right":
    print(''' GAME OVER: You didn't see the hole and fell to your death.
                 .... NO! ...                  ... MNO! ...
               ..... MNO!! ...................... MNNOO! ...
             ..... MMNO! ......................... MNNOO!! .
            ..... MNOONNOO!   MMMMMMMMMMPPPOII!   MNNO!!!! .
             ... !O! NNO! MMMMMMMMMMMMMPPPOOOII!! NO! ....
                ...... ! MMMMMMMMMMMMMPPPPOOOOIII! ! ...
               ........ MMMMMMMMMMMMPPPPPOOOOOOII!! .....
               ........ MMMMMOOOOOOPPPPPPPPOOOOMII! ...
                ....... MMMMM..    OPPMMP    .,OMI! ....
                 ...... MMMM::   o.,OPMP,.o   ::I!! ...
                     .... NNM:::.,,OOPM!P,.::::!! ....
                      .. MMNNNNNOOOOPMO!!IIPPO!!O! .....
                     ... MMMMMNNNNOO:!!:!!IPPPPOO! ....
                       .. MMMMMNNOOMMNNIIIPPPOO!! ......
                      ...... MMMONNMMNNNIIIOO!..........
                   ....... MN MOMMMNNNIIIIIO! OO ..........
                ......... MNO! IiiiiiiiiiiiI OOOO ...........
              ...... NNN.MNO! . O!!!!!!!!!O . OONO NO! ........
               .... MNNNNNO! ...OOOOOOOOOOO .  MMNNON!........
               ...... MNNNNO! .. PPPPPPPPP .. MMNON!........
                  ...... OO! ................. ON! .......
                     ................................
            ''')
elif chosen_path == "left":
    print("You go left and find yourself at a glowing river full of bioluminescent plants and fish.")
    water = input("Do you choose to swim across or wait for a boat?\n Type 'swim' or 'wait' to make your choice\n")
    if water == "wait":
        print("You see a row boat on the bank and cross safely. You find yourself in front of three dungeon doors.")
        chosen_door = input("One yellow, one red, and one blue. Which door do you choose? Type the colour.\n")
        if chosen_door == "blue":
            print(''' GAME OVER:You were eaten by a Dragon.\n
                           _(.==.         .==.)_
                            //`^\\(\_._/)//^`\\
                           //^ ^ ^( 6 6 )^ ^ ^\\
                          //^ ^ ^/\( " )/\^ ^ ^\\
                         // ^ /\/_/ v"v \_\/\^  \\
                         \\^ /  // /===\ \\  \ ^//
                          \\/   \(((===)))/   \//
                           ^   .-' /\__/\ `-.  ^
                              (((-'      '-)))
                        ''')
        elif chosen_door == "red":
            print(''' GAME OVER: You stumble into a witches lair and she sets you ablaze turning you to ash.\n
            
                                 Double,double
                                 Toil and trouble
               (       "     )   Fire burn and
                ( _  *           Cauldron bubble
                   * (     /      \    ___
                      "     "        _/ /
                     (   *  )    ___/   |
                       )   "     _ o)'-./__
                      *  _ )    (_, . $$$
                      (  )   __ __ 7_ $$$$
                       ( :  { _)  '---  $|
                  ______'___//__\   ____,|
                   )           ( \_/ _____\_
                 .'             \   \------''.
                 |='           '=|  |         )
                 |               |  |  .    _/
                  \    (. ) ,   /  /__I_____|
                   '._/_)_(\__.'   (__,(__,_]
                  @---()_.'---@
                  \n''')
        elif chosen_door == "yellow":
            print(''' CONGRATULATIONS\nYou Win.\n
            | |_ _ __ ___  __ _ ___ _   _ _ __ ___ 
            | __| '__/ _ \/ _` / __| | | | '__/ _ \.
            | |_| | |  __/ (_| \__ \ |_| | | |  __/
            \__|_|  \___|\__,_|___/\__,_|_|  \___|
             _____ ____ _____
            /    /      \    \.
          /____ /_________\____\.
          \    \          /    /
             \  \        /  /
               \ \    / /
                  \ \/ /
                    \/
                    \n''')
        else:
            print('''          GAME OVER.
                 .... NO! ...                  ... MNO! ...
               ..... MNO!! ...................... MNNOO! ...
             ..... MMNO! ......................... MNNOO!! .
            ..... MNOONNOO!   MMMMMMMMMMPPPOII!   MNNO!!!! .
             ... !O! NNO! MMMMMMMMMMMMMPPPOOOII!! NO! ....
                ...... ! MMMMMMMMMMMMMPPPPOOOOIII! ! ...
               ........ MMMMMMMMMMMMPPPPPOOOOOOII!! .....
               ........ MMMMMOOOOOOPPPPPPPPOOOOMII! ...
                ....... MMMMM..    OPPMMP    .,OMI! ....
                 ...... MMMM::   o.,OPMP,.o   ::I!! ...
                     .... NNM:::.,,OOPM!P,.::::!! ....
                      .. MMNNNNNOOOOPMO!!IIPPO!!O! .....
                     ... MMMMMNNNNOO:!!:!!IPPPPOO! ....
                       .. MMMMMNNOOMMNNIIIPPPOO!! ......
                      ...... MMMONNMMNNNIIIOO!..........
                   ....... MN MOMMMNNNIIIIIO! OO ..........
                ......... MNO! IiiiiiiiiiiiI OOOO ...........
              ...... NNN.MNO! . O!!!!!!!!!O . OONO NO! ........
               .... MNNNNNO! ...OOOOOOOOOOO .  MMNNON!........
               ...... MNNNNO! .. PPPPPPPPP .. MMNON!........
                  ...... OO! ................. ON! .......
                     ................................
            \n''')
    else:
        print(''' GAME OVER: You become tangled in the pretty glowing plants while swimming and drown.  
         .                    .                    .                    .
        :                    :                    :                    :
        :    .               :    .               :    .               :
       .'   .   .           .'   .   .           .'   .   .           .'   .
      . '   .' O.'   .      .'   .O  .'   .      .'  O.'  .'   .      .'O  .'
     .'   .'  .'  ..      .'   .'  .'  ..      .'   .'  .'  ..      .'   .'
     ::   :   .O ..       ::   :  O.' ..       ::   :O  .' ..       ::  O:
     : \. '   :  :         \. .'   :  :        \.  .'   :  :       \.   .'
   \,  ;\\,,  :O '.    \,  ;\\,,  O:  '.   \,  ;\\,, O :   '.  \,  ;\\,,O'
    \\::333:o  .  ''    \\::333:o  '.  ''   \\::333:o   '.  ''  \\::333:o
   , /:33333:< :  ,      /:33333:<  ,   :    /:33333:<,  ::  :   /:33333:<
    ' '///''    .:/     ' '///''  .:/   :   ' '///''.:/  .'  :  ' '///'' ::
       /  :: ,,///;,  ,/   /   ,,///;,  ,/ .:  / ,,///;,  ,/ '. .: /     ::
         .' o:33333:://       o:33333::// . :   o:33333:://   '. :      .''
        .' >:3333333:\\      >:3333333:\\ ::   >:3333333:\\    ::      .'  .
       .'    ''\\\\\" '\       ''\\\\\" '\ :     ''\\\\\" '\   ::     .'   :
       ::    '. ';\  ' '\   ::    ';\  . '\ '    :: ';\ .  '\ .' '    ::
       ':..   ' ,. '' :     ':..   ' ,.:'' :     ':..   ' ,.:'' :     ':..
        :::    .''   ::      :::    .''   ::      :::    .''   ::      :::
        :::  .:' .  .'       :::  .:' .  .'       :::  .:' .  .'       :::
        ::: :::  ::::        ::: :::  ::::        ::: :::  ::::        ::: :
    ''')
else:
    print(''' GAME OVER: You didn't see the hole and fell to your death.
     .... NO! ...                  ... MNO! ...
   ..... MNO!! ...................... MNNOO! ...
 ..... MMNO! ......................... MNNOO!! .
..... MNOONNOO!   MMMMMMMMMMPPPOII!   MNNO!!!! .
 ... !O! NNO! MMMMMMMMMMMMMPPPOOOII!! NO! ....
    ...... ! MMMMMMMMMMMMMPPPPOOOOIII! ! ...
   ........ MMMMMMMMMMMMPPPPPOOOOOOII!! .....
   ........ MMMMMOOOOOOPPPPPPPPOOOOMII! ...
    ....... MMMMM..    OPPMMP    .,OMI! ....
     ...... MMMM::   o.,OPMP,.o   ::I!! ...
         .... NNM:::.,,OOPM!P,.::::!! ....
          .. MMNNNNNOOOOPMO!!IIPPO!!O! .....
         ... MMMMMNNNNOO:!!:!!IPPPPOO! ....
           .. MMMMMNNOOMMNNIIIPPPOO!! ......
          ...... MMMONNMMNNNIIIOO!..........
       ....... MN MOMMMNNNIIIIIO! OO ..........
    ......... MNO! IiiiiiiiiiiiI OOOO ...........
  ...... NNN.MNO! . O!!!!!!!!!O . OONO NO! ........
   .... MNNNNNO! ...OOOOOOOOOOO .  MMNNON!........
   ...... MNNNNO! .. PPPPPPPPP .. MMNON!........
      ...... OO! ................. ON! .......
         ................................
''')
